#!venv/bin/python3.7

import urllib.request
from lxml import html
import sys

contents = urllib.request.urlopen("https://weather.com/weather/today/l/{}:4:US".format(sys.argv[1])).read()
tree = html.fromstring(contents)
description = tree.xpath('//*[contains(@id, "main-Nowcard-")]/div/div/section/div[2]/div[1]/div[3]/text()')[0]
temp = int(tree.xpath('//*[contains(@id, "main-Nowcard-")]/div/div/section/div[2]/div[1]/div[2]/span/text()')[0])
temp_adj = int(round((temp - 32)*5/9 + 273.15, 0))
print('{} {} degrees Kelvin'.format(description, temp_adj))